### ISSUE TITLE
[Enhancement] Idea KCL Plugin Build on 233+ version including Ultimate and Community Edition

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/intellij-kcl#21]
+ [ ] Plugin Release 0.1.15 does not work on 232 Community Edition because of the deps `https://github.com/kcl-lang/intellij-kcl/pull/12` in PR https://github.com/kcl-lang/intellij-kcl/pull/12

![image](https://github.com/kcl-lang/intellij-kcl/assets/22744597/38803a4e-8b62-492a-905b-64712978afaf)

+ [ ] Plugin Release 0.1.5 does not work on 233+ version including Ultimate and Community Edition
+ [ ] LSP Features do not work on 232.2 Ultimate version

**Comment by alloveras** [comment]
Hello @Peefy,
I tried the plugin for `pluginUntilBuild = 233.*` and `platformVersion = 2023.3.2` from the `main` branch and it seems to work. I suspect this is because the `lsp` dependencies that you mention on the first bullet point in the issue description are in the `lsp` branch.

I wonder what's the plan to resolve the build failures on the `lsp` branch since JetBrains seems to [make it very clear](https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/#supported-ides) that LSP support will only be available in the paid versions of their IDEs (which effectively means: no Community Edition).

Thanks in advance!

**Comment by Peefy** [comment]
ping @He1pa

**Comment by He1pa** [comment]
> Hello @Peefy, I tried the plugin for `pluginUntilBuild = 233.*` and `platformVersion = 2023.3.2` from the `main` branch and it seems to work. I suspect this is because the `lsp` dependencies that you mention on the first bullet point in the issue description are in the `lsp` branch.
> 
> I wonder what's the plan to resolve the build failures on the `lsp` branch since JetBrains seems to [make it very clear](https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/#supported-ides) that LSP support will only be available in the paid versions of their IDEs (which effectively means: no Community Edition).
> 
> Thanks in advance!

You are right, the build failure problem occurs in the `lsp` branch. But I have fixed this problem and published a new version plugin in IDEA Marketplace. Now it's time to close this Issue. But anyway, thank you for your support.

**Comment by alloveras** [comment]
Do you mind pointing me to where the new plugin version has been released?

I could not find it either in this repository releases list nor in the IntelliJ marketplace 😅?

**Comment by He1pa** [comment]
> Do you mind pointing me to where the new plugin version has been released?
> 
> I could not find it either in this repository releases list nor in the IntelliJ marketplace 😅?

you can build it from 'lsp' branch or search it from marketplace
https://plugins.jetbrains.com/plugin/23378-kcl
![image](https://github.com/kcl-lang/intellij-kcl/assets/56333845/fec3f71a-cb5d-4681-b484-394efd9eee28)
